name: Executable Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.12
  POETRY_VERSION: 1.8.3

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'
      - run: |
          pipx install poetry==${{ env.POETRY_VERSION }}
          poetry install

      # Build python script into a stand-alone exe
      - uses: Nuitka/Nuitka-Action@main
        with:
          script-name: main.py
          onefile: true
          enable-plugins: pyside6
          disable-console: true
          macos-create-app-bundle: true

      # Uploads artifact
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
