name: Executable Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.12
  POETRY_VERSION: 1.8.3

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry==${{ env.POETRY_VERSION }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'
      - run: poetry install
      - run: poetry run ruff check

  behave:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry==${{ env.POETRY_VERSION }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'
      - run: sudo apt update && sudo apt install -y libegl1-mesa-dev libxkbcommon-x11-0
      - run: poetry install
      - run: poetry run behave
        env:
          QT_DEBUG_PLUGINS: 1

  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: [ruff, behave]
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: |
          pipx install poetry==${{ env.POETRY_VERSION }}
          pipx inject poetry poetry-plugin-export
      - name: Export poetry
        run: poetry export -f requirements.txt -o requirements.txt
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
      - run: pip install -r requirements.txt

      # Build python script into a stand-alone exe
      - uses: Nuitka/Nuitka-Action@main
        with:
          script-name: Quill.py
          onefile: true
          enable-plugins: pyside6
          disable-console: true
          macos-create-app-bundle: true

      # Uploads artifact
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          include-hidden-files: true
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
